#!/bin/bash
#
# pp4ml - a m4 based preprocessor for ocaml
# Copyright (C) 2015 -- M E Leypold
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

MYNAME="$0"

case "$0" in
    /*) ;;
   */*) MYNAME="$(/bin/pwd)/$MYNAME" ;;
     *) MYNAME="$(which "$MYNAME")" ;;
esac

MYPATH="$(dirname $MYNAME)"
if test -f "$MYNAME".m4; then # hardcoded search for macro definitions
    M4LIBDIR="$MYPATH"
else
    M4LIBDIR="$(dirname "$MYPATH")/share/pp4ml"
fi

exec m4 -s -P "$M4LIBDIR"/pp4ml.m4 "$@" | sed 's|^#line |#|'
